// src/lib/components/Header.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import Logo from '../assets/echo-logo-black.svg?component';
</script>

<header class="flex p-5 md:p-10 transition-all duration-150 items-center">
	<div class="flex">
		<a href="/">
			<Logo width={75} height={75} />
		</a>
	</div>
	<div class="flex-1" />
	<nav class="flex-0 flex gap-2">
		<a
			class="h-10 w-10 p-1 rounded-lg hover:bg-gray-300 transition-colors duration-200"
			href="https://github.com/echo-webkom"
		>
			<span class="sr-only">GitHub</span>
			<Icon class="h-full w-full" icon="mdi:github" />
		</a>
		<a
			class="h-10 w-10 p-1 rounded-lg hover:bg-gray-300 transition-colors duration-200"
			href="https://www.instagram.com/echo_webkom"
		>
			<span class="sr-only">Instagram</span>
			<Icon class="h-full w-full" icon="mdi:instagram" />
		</a>
	</nav>
</header>

// src/components/header/header.tsx
import Image from "next/image";
import Link from "next/link";
import logo from "../../../public/images/echo-negativ.png";
import IconLink from "./icon-link";
import { AiFillGithub } from "react-icons/ai";
import { BsInstagram } from "react-icons/bs";
import { IoMdPerson } from "react-icons/io";

const Header = () => (
  <div className="flex flex-row justify-between items-center w-full py-5 px-5 md:px-10 z-10">
    <div>
      <div className="relative h-20 w-20">
        <Link href="https://echo.uib.no" passHref>
          <a>
            <Image src={logo} alt="echo logo" objectFit="fill" layout="fill" />
          </a>
        </Link>
      </div>
    </div>
    <div className="flex flex-row gap-5 items-center">
      <IconLink
        to="https://github.com/echo-webkom"
        icon={
          <IoMdPerson
            size={30}
            className="text-gray-400 transition-colors duration-200 hover:text-white"
          />
        }
      />
      <IconLink
        to="https://github.com/echo-webkom"
        icon={
          <AiFillGithub
            size={30}
            className="text-gray-400 transition-colors duration-200 hover:text-white"
          />
        }
      />
      <IconLink
        to="https://instagram.com/echo_webkom"
        icon={
          <BsInstagram
            size={30}
            className="text-gray-400 transition-colors duration-200 hover:text-white"
          />
        }
      />
    </div>
  </div>
);

export default Header;
