// src/lib/components/Header.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import Logo from '../assets/echo-logo-black.svg?component';
</script>

<header class="flex p-5 md:p-10 transition-all duration-150 items-center">
	<div class="flex">
		<a href="/">
			<Logo width={75} height={75} />
		</a>
	</div>
	<div class="flex-1" />
	<nav class="flex-0 flex gap-2">
		<a
			class="h-10 w-10 p-1 rounded-lg hover:bg-gray-300 transition-colors duration-200"
			href="https://github.com/echo-webkom"
		>
			<span class="sr-only">GitHub</span>
			<Icon class="h-full w-full" icon="mdi:github" />
		</a>
		<a
			class="h-10 w-10 p-1 rounded-lg hover:bg-gray-300 transition-colors duration-200"
			href="https://www.instagram.com/echo_webkom"
		>
			<span class="sr-only">Instagram</span>
			<Icon class="h-full w-full" icon="mdi:instagram" />
		</a>
	</nav>
</header>

// src/components/header/index.tsx
import Link from "next/link";
import EchoLogo from "../../../public/svg/echo-logo-white.svg";
import IconLink from "./icon-link";
import { AiFillGithub } from "react-icons/ai";
import { BsInstagram } from "react-icons/bs";

const Header = () => (
  <header className="flex flex-row justify-between items-center w-full py-5 md:py-10 px-5 md:px-20 transition-all duration-300">
    <Link href="/" passHref>
      <a>
        <EchoLogo className="w-20 h-20" />
      </a>
    </Link>
    <nav className="flex flex-row gap-5 items-center">
      <IconLink
        to="https://github.com/echo-webkom"
        icon={
          <AiFillGithub
            size={25}
            className="text-gray-400 transition-colors duration-200 hover:text-white"
          />
        }
      />
      <IconLink
        to="https://instagram.com/echo_webkom"
        icon={
          <BsInstagram
            size={25}
            className="text-gray-400 transition-colors duration-200 hover:text-white"
          />
        }
      />
    </nav>
  </header>
);

export default Header;
